pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.PREFER_SETTINGS
    repositories { mavenCentral() }
}

rootProject.name = "RimWorldCraft"
include("core-api", "core-impl", "infrastructure-common")
