plugins {
    id 'java-library'
}

dependencies {
    api project(':core-api')
    implementation project(':core-impl')
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${jacksonVersion}"
    implementation "com.networknt:json-schema-validator:${networkntSchemaVersion}"
    implementation "org.slf4j:slf4j-api:${slf4jVersion}"
    testImplementation platform("org.junit:junit-bom:${junitVersion}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation "org.mockito:mockito-core:${mockitoVersion}"
    testImplementation "org.assertj:assertj-core:${assertjVersion}"
}

tasks.register('configTest', Test) { include '**/*ConfigurationSmokeTest.class' }
tasks.register('configSchemaTest', Test) { include '**/*ConfigurationSmokeTest.class' }
tasks.register('configMutationTest', Test) { include '**/*ConfigurationSmokeTest.class' }
check.dependsOn(configTest, configSchemaTest, configMutationTest)
