package com.rimworldcraft.core.building;
import com.rimworldcraft.core.api.events.*;import com.rimworldcraft.core.api.types.*;import java.util.*;
public final class BuildOrder {
 private final UUID id,colonyId;private final Blueprint blueprint;private final GridPosition target;private final int priority;private final Map<ResourceType,Integer> consumed=new EnumMap<>(ResourceType.class);private final Set<UUID> assigned=new LinkedHashSet<>();private final Set<UUID> results=new HashSet<>();private BuildOrderStatus status=BuildOrderStatus.PENDING;private int progress;
 public BuildOrder(UUID id,UUID colonyId,Blueprint blueprint,GridPosition target,int priority){this.id=Objects.requireNonNull(id);this.colonyId=Objects.requireNonNull(colonyId);this.blueprint=Objects.requireNonNull(blueprint);this.target=Objects.requireNonNull(target);if(priority<0)throw new IllegalArgumentException("priority");this.priority=priority;}
 public BuildOrder(UUID id,UUID colonyId,String blueprintId,Position target,int priority,Map<ResourceType,Integer> required){this(id,colonyId,new Blueprint(blueprintId,blueprintId,blueprintId,1,1,1,required,0),new GridPosition(target.x(),target.y(),target.z()),priority);}
 public UUID id(){return id;}public UUID colonyId(){return colonyId;}public Blueprint blueprint(){return blueprint;}public GridPosition target(){return target;}public int priority(){return priority;}public BuildOrderStatus status(){return status;}public int progress(){return progress;}public Set<UUID> assignedCitizens(){return Set.copyOf(assigned);}public Map<ResourceType,Integer> consumed(){return Map.copyOf(consumed);}public UUID getId(){return id;}public BuildOrderStatus getStatus(){return status;}public int getProgress(){return progress;}public List<UUID> getAssignedCitizenIds(){return List.copyOf(assigned);}
 public void reserve(){if(status!=BuildOrderStatus.PENDING)throw new IllegalStateException("cannot reserve");status=BuildOrderStatus.RESERVED;}
 public List<DomainEvent> assignCitizen(UUID citizen){if(status==BuildOrderStatus.COMPLETED||status==BuildOrderStatus.CANCELLED||status==BuildOrderStatus.FAILED)throw new IllegalStateException("closed");if(assigned.add(Objects.requireNonNull(citizen)))status=BuildOrderStatus.IN_PROGRESS;return List.of(new BuildOrderAssignedEvent(id));}
 public void updateProgress(int delta){if(status==BuildOrderStatus.FAILED||status==BuildOrderStatus.CANCELLED||status==BuildOrderStatus.COMPLETED)throw new IllegalStateException("closed");if(delta<0||progress+delta>100)throw new IllegalArgumentException("progress 0..100");progress+=delta;}
 public boolean applyResourceResult(UUID resultId,ResourceType type,int amount){if(!results.add(Objects.requireNonNull(resultId)))return false;if(amount<0||amount>blueprint.requiredResources().getOrDefault(type,0)-consumed.getOrDefault(type,0))throw new IllegalArgumentException("invalid consumption");consumed.merge(type,amount,Integer::sum);return true;}public void consumeResource(ResourceType type,int amount){applyResourceResult(UUID.randomUUID(),type,amount);}
 public List<DomainEvent> complete(){if(progress<100)throw new IllegalStateException("incomplete");if(status==BuildOrderStatus.COMPLETED)return List.of();if(status==BuildOrderStatus.FAILED||status==BuildOrderStatus.CANCELLED)throw new IllegalStateException("closed");status=BuildOrderStatus.COMPLETED;return List.of(new BuildOrderCompletedEvent(id));}
 public List<DomainEvent> cancel(String reason){if(status==BuildOrderStatus.COMPLETED)throw new IllegalStateException("completed order cannot be cancelled");if(status!=BuildOrderStatus.FAILED)status=BuildOrderStatus.CANCELLED;return List.of(new BuildOrderCancelledEvent(id));}public void cancel(){cancel("");}public List<DomainEvent> fail(String reason){if(status!=BuildOrderStatus.COMPLETED)status=BuildOrderStatus.FAILED;return List.of(new BuildOrderFailedEvent(id));}public void fail(){fail("");}
}
