plugins {
    id 'java-library'
}

dependencies {
    api project(':core-api')
    implementation "org.slf4j:slf4j-api:${slf4jVersion}"
    testImplementation platform("org.junit:junit-bom:${junitVersion}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation "org.mockito:mockito-core:${mockitoVersion}"
    testImplementation "org.assertj:assertj-core:${assertjVersion}"
}
